# This file has been autogenerated by the pywayland scanner

# Copyright © 2015 Martin Gräßlin
# Copyright © 2022 Simon Ser
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

from __future__ import annotations

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource

from .wayland import WlSeat
from .wayland import WlSeatProxy


class ExtIdleNotificationV1(Interface):
    """Idle notification

    This interface is used by the compositor to send idle notification events
    to clients.

    Initially the notification object is not idle. The notification object
    becomes idle when no user activity has happened for at least the timeout
    duration, starting from the creation of the notification object. User
    activity may include input events or a presence sensor, but is compositor-
    specific.

    How this notification responds to idle inhibitors depends on how it was
    constructed. If constructed from the get_idle_notification request, then if
    an idle inhibitor is active (e.g. another client has created a
    zwp_idle_inhibitor_v1 on a visible surface), the compositor must not make
    the notification object idle. However, if constructed from the
    get_input_idle_notification request, then idle inhibitors are ignored, and
    only input from the user, e.g. from a keyboard or mouse, counts as
    activity.

    When the notification object becomes idle, an idled event is sent. When
    user activity starts again, the notification object stops being idle, a
    resumed event is sent and the timeout is restarted.
    """

    name = "ext_idle_notification_v1"
    version = 2


class ExtIdleNotifierV1(Interface):
    """Idle notification manager

    This interface allows clients to monitor user idle status.

    After binding to this global, clients can create
    :class:`~pywayland.protocol.ext_idle_notify_v1.ExtIdleNotificationV1`
    objects to get notified when the user is idle for a given amount of time.
    """

    name = "ext_idle_notifier_v1"
    version = 2


class ExtIdleNotificationV1Resource(Resource[ExtIdleNotificationV1]):
    interface = ExtIdleNotificationV1

    @ExtIdleNotificationV1.event()
    def idled(self) -> None:
        """Notification object is idle

        This event is sent when the notification object becomes idle.

        It's a compositor protocol error to send this event twice without a
        resumed event in-between.
        """
        self._post_event(0)

    @ExtIdleNotificationV1.event()
    def resumed(self) -> None:
        """Notification object is no longer idle

        This event is sent when the notification object stops being idle.

        It's a compositor protocol error to send this event twice without an
        idled event in-between. It's a compositor protocol error to send this
        event prior to any idled event.
        """
        self._post_event(1)


class ExtIdleNotifierV1Resource(Resource[ExtIdleNotifierV1]):
    interface = ExtIdleNotifierV1


class ExtIdleNotificationV1Proxy(Proxy[ExtIdleNotificationV1]):
    interface = ExtIdleNotificationV1

    @ExtIdleNotificationV1.request()
    def destroy(self) -> None:
        """Destroy the notification object

        Destroy the notification object.
        """
        self._marshal(0)
        self._destroy()


class ExtIdleNotifierV1Proxy(Proxy[ExtIdleNotifierV1]):
    interface = ExtIdleNotifierV1

    @ExtIdleNotifierV1.request()
    def destroy(self) -> None:
        """Destroy the manager

        Destroy the manager object. All objects created via this interface
        remain valid.
        """
        self._marshal(0)
        self._destroy()

    @ExtIdleNotifierV1.request(
        Argument(ArgumentType.NewId, interface=ExtIdleNotificationV1),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSeat),
    )
    def get_idle_notification(self, timeout: int, seat: WlSeatProxy) -> ExtIdleNotificationV1Proxy:
        """Create a notification object

        Create a new idle notification object.

        The notification object has a minimum timeout duration and is tied to a
        seat. The client will be notified if the seat is inactive for at least
        the provided timeout. See
        :class:`~pywayland.protocol.ext_idle_notify_v1.ExtIdleNotificationV1`
        for more details.

        A zero timeout is valid and means the client wants to be notified as
        soon as possible when the seat is inactive.

        :param timeout:
            minimum idle timeout in msec
        :type timeout:
            `ArgumentType.Uint`
        :param seat:
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        :returns:
            :class:`~pywayland.protocol.ext_idle_notify_v1.ExtIdleNotificationV1`
        """
        id = self._marshal_constructor(1, ExtIdleNotificationV1, timeout, seat)
        return id

    @ExtIdleNotifierV1.request(
        Argument(ArgumentType.NewId, interface=ExtIdleNotificationV1),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Object, interface=WlSeat),
        version=2,
    )
    def get_input_idle_notification(self, timeout: int, seat: WlSeatProxy) -> ExtIdleNotificationV1Proxy:
        """Create a notification object

        Create a new idle notification object to track input from the user,
        such as keyboard and mouse movement. Because this object is meant to
        track user input alone, it ignores idle inhibitors.

        The notification object has a minimum timeout duration and is tied to a
        seat. The client will be notified if the seat is inactive for at least
        the provided timeout. See
        :class:`~pywayland.protocol.ext_idle_notify_v1.ExtIdleNotificationV1`
        for more details.

        A zero timeout is valid and means the client wants to be notified as
        soon as possible when the seat is inactive.

        :param timeout:
            minimum idle timeout in msec
        :type timeout:
            `ArgumentType.Uint`
        :param seat:
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        :returns:
            :class:`~pywayland.protocol.ext_idle_notify_v1.ExtIdleNotificationV1`
        """
        id = self._marshal_constructor(2, ExtIdleNotificationV1, timeout, seat)
        return id


class ExtIdleNotificationV1Global(Global[ExtIdleNotificationV1]):
    interface = ExtIdleNotificationV1


class ExtIdleNotifierV1Global(Global[ExtIdleNotifierV1]):
    interface = ExtIdleNotifierV1


ExtIdleNotificationV1._gen_c()
ExtIdleNotificationV1.proxy_class = ExtIdleNotificationV1Proxy
ExtIdleNotificationV1.resource_class = ExtIdleNotificationV1Resource
ExtIdleNotificationV1.global_class = ExtIdleNotificationV1Global


ExtIdleNotifierV1._gen_c()
ExtIdleNotifierV1.proxy_class = ExtIdleNotifierV1Proxy
ExtIdleNotifierV1.resource_class = ExtIdleNotifierV1Resource
ExtIdleNotifierV1.global_class = ExtIdleNotifierV1Global
